#!/usr/bin/env bash
# Installs Nginx
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html/
sudo service nginx start
# Config for index.html
echo 'Holberton School for the win!' > temp_config.html
sudo cp temp_config.html /var/www/html/index.html
rm temp_config.html
# Redirect
redirect="location /redirect_me {\\nrewrite ^(.*)$ http://www.quotationspage.com/random.php permanent;\\n}"
sudo sed -i "30i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
