#!/usr/bin/env bash
# Installs Nginx
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html/
sudo service nginx start
# Config for index
echo 'Holberton School for the win!' > temp_config.html
sudo cp temp_config.html /var/www/html/index.html
rm temp_config.html
# Config for 404
sudo mkdir -p /var/www/err/html
sudo touch /var/www/err/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/err/html/404.html
# Redirect
redirect="location /redirect_me {\\nrewrite ^(.*)$ http://www.quotationspage.com/random.php permanent;\\n}"
sudo sed -i "30i $redirect" /etc/nginx/sites-available/default
error_404="error_page 404 /pnf_404.html;\nlocation = /pnf_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "33i $error_404" /etc/nginx/sites-available/default
sudo service nginx restart
