#!/usr/bin/env bash
# This script will create a pid, print a message indefinitely...
# Prints different message when SIGTERM or SIGINT is recieved
# Will delete pid & terminate upon recieving SIGQUIT or SIGTERM

echo $$ > /var/run/holbertonscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit 0" SIGTERM
trap "sudo rm /var/run/holbertonscript.pid; exit 0" SIGQUIT

while true
do
        echo "To infinity and beyond"
        sleep 2
done
