#!/usr/bin/env bash
# This script displays a string on loop indefinitely
# Prints a new message upon recieving sigterm signal

trap "echo I am invincible!!!" SIGTERM
buzz="To infinity and beyond"

while true
do
        echo "$buzz"
        sleep 2
done
