#!/usr/bin/env bash
# This script loops from 1-10, with custom messages 
# The 4th loop displays "bad luck"
# The 8th loop displays "good luck"
# All others display "Holberton School"

string_count=1
bad_string='bad luck'
good_string='good luck'
holby_string='Holberton School'

while [ $string_count -le 10 ]
do
    if [ $string_count -eq 4 ]
    then
        echo "$bad_string"
        ((string_count++))
    elif [ $string_count -eq 8 ]
    then
        echo "$good_string"
        ((string_count++))
    else
        echo "$holby_string"
        ((string_count++))
    fi
done
