#!/usr/bin/env bash
# This script will display numbers 1-20
# Specific messages after #'s 4,9,17

num_count=1
bad_china='bad luck from China'
bad_japan='bad luck from Japan'
bad_italy='bad luck from Italy'

while [ $num_count -le 20 ]
do
    echo "$num_count"
    case "$num_count" in 
    4) echo "$bad_china"
        ;;
    9) echo "$bad_japan"
        ;;
    17) echo "$bad_italy"
        ;;
    esac
    ((num_count++))
done
