#!/usr/bin/env bash
# This script will retrieve information about a file

file="holbertonschool"
exists='holbertonschool file exists'
not_exist='holbertonschool file does not exist'
not_empty='holbertonschool file is not empty'
empty='holbertonschool file is empty'
regular='holbertonschool is a regular file'

if [ -e $file ]
then
    echo "$exists"
    if [ -s $file ]
    then
        echo "$not_empty"
    else
        echo "$empty"
    fi
    if [ -f $file ]
    then
        echo "$regular"
    fi
else
    echo "$not_exist"
fi
